debug: false

server:
  port: 9264

src:
  inputs:
    enabled: true
    hotPlug: false
    pattern: ".*"
  makcu:
    enabled: false
    baudrate: 4000000
    ttyPath: /dev/ttyACM0
  udp:
    enabled: true
    port: 9265
dst:
  kcom5:
    baudrate: 2000000
    ttyPath: /dev/ttyUSB0
    sbdesc: 
    csdesc: 
    cpdesc: 
    xldesc: 
  makcu:
    baudrate: 4000000
    ttyPath: /dev/ttyACM1
  udp:
    ip: 192.168.3.64
    port: 61069
  uds:
    address: uds_mouse_keyboard_event_socket
  uinput:
    deviceName: input2com
  usbgadget:
    mouseFile: /dev/input/hidg0
    keyboardFile: /dev/input/hidg1
usingDst: makcu
